name: weathery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: ^0.17.0
  location: ^4.4.0
  lottie: ^2.0.0
  shimmer: ^2.0.0
  dio: ^4.0.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: RobotoSlab-Black
      fonts:
        - asset: assets\fonts\RobotoSlab-Black.ttf
    - family: RobotoSlab-Bold
      fonts:
        - asset: assets\fonts\RobotoSlab-Bold.ttf
    - family: RobotoSlab-ExtraBold
      fonts:
        - asset: assets\fonts\RobotoSlab-ExtraBold.ttf
    - family: RobotoSlab-ExtraLight
      fonts:
        - asset: assets\fonts\RobotoSlab-ExtraLight.ttf
    - family: RobotoSlab-Light
      fonts:
        - asset: assets\fonts\RobotoSlab-Light.ttf
    - family: RobotoSlab-Medium
      fonts:
        - asset: assets\fonts\RobotoSlab-Medium.ttf
    - family: RobotoSlab-Regular
      fonts:
        - asset: assets\fonts\RobotoSlab-Regular.ttf
    - family: RobotoSlab-SemiBold
      fonts:
        - asset: assets\fonts\RobotoSlab-SemiBold.ttf
    - family: RobotoSlab-Thin
      fonts:
        - asset: assets\fonts\RobotoSlab-Thin.ttf
   
